# Trading Configuration
trading:
  symbols: ["BTCUSDT", "ETHUSDT"]
  timeframe: "5m"
  risk_per_trade: 0.5  # % of capital to risk per trade

# Strategy Parameters
strategy:
  tdi:
    rsi_period: 10
    bb_length: 20
    hard_buy_zone: 25
    soft_buy_zone: 35
    no_trade_zone: [45, 55]
    soft_sell_zone: 65
    hard_sell_zone: 75
  
  bollinger:
    length: 34
    trend_line_period: 9
    dev: 1.75
    atr_period: 1
    atr_multiplier: 0.9

# Data Settings
data:
  history_days: 7
  update_interval: 300  # seconds
